### ISSUE TITLE
compatible with 2.0" version

### ISSUE THREAD

**Issue by avandalen** [Nkawu/TFT_22_ILI9225#21]
It seems that the 2.2 inch TFT is outdated and no longer being made. The 2.2" is hard to find now. More frequent you see the 2.0" TFT, which seems equal but smaller. Do you think that the library works for the 2.0"also?
https://www.ebay.com/itm/ILI9225-2-0-Inch-TFT-Display-Module-Serial-Port-SPI-Interface-Applied-176x220-/302188734615?hash=item465bda2897:g:r8sAAOSw5cNYb0Lf

**Comment by Nkawu** [comment]
The resolution is the same at 176x220, so I don't see why it wouldn't work

**Comment by avandalen** [comment]
Yes I see no problems eather
