### ISSUE TITLE
Call to invert appears non-functional

### ISSUE THREAD

**Issue by Aquidneck** [Nkawu/TFT_22_ILI9225#30]
Regardless of where invoked in code (prior to writing to display, or after) there's no display inversion taking place.  Is this function working for anyone, and if so, please provide a code example

**Comment by Nkawu** [comment]
Which board are you using?

**Comment by Aquidneck** [comment]
HiLetgo 2.2" ILI9225 purchased from Amazon.  It’s a non-issue for my application (colored text only) since I mounted it in the project enclosure in the proper orientation...
