### ISSUE TITLE
touchscreen?

### ISSUE THREAD

**Issue by lutfisan** [Nkawu/TFT_22_ILI9225#34]
is it support touchscreen?

it is 4 wires cable for resistive touchscreen?

![ili9255](https://user-images.githubusercontent.com/29010489/46567844-fdfe1580-c964-11e8-8dd1-14381027686d.PNG)

**Comment by Nkawu** [comment]
The library doesn't support touchscreen and I don't know if the module does. Feel free to write the touchscreen code if you figure out it does support that!
