### ISSUE TITLE
Bug in fastmode

### ISSUE THREAD

**Issue by Bolukan** [Nkawu/TFT_22_ILI9225#43]
Hi again,

I discovered another bug. drawChar applies startWrite/checkSPI but if fastmode becomes enabled, the code calls _setWindow, which also calls startWrite. Hence a hangup.

Before proposing a pull request (currently I disable fastMode), I wonder how we are supposed to deal with these startWrite/checkSPI functions. 
The current idea is that only the first function opens the SPI transaction. But as also helper functions can be called directly themselves (p.e. drawText calls drawChar, drawChar calls _setWindows, etc), the code has to check whether it is a main function or a helper function. 

@Nkawu (or others): how to proceed?

PS: For example use a counter: only '0' starts the transaction, and helpers '1' or helper-helpers '2', etc only transmit.

**Comment by Nkawu** [comment]
Yes please do. Thank you for taking the lead on this, unfortunately I don't have too much time to spend on personal projects any more.

**Comment by Bolukan** [comment]
solved see #44
