### ISSUE TITLE
Faster refresh rate

### ISSUE THREAD

**Issue by Xx-shunya-xX** [Nkawu/TFT_22_ILI9225#70]
Hello NKawu,
I was trying to make a game on ili9225 using arduino leonardo, I noticed when using tft.clear() functions it uses fillRectangle() function with COLOR_BLACK to clear the whole screen. But I want a faster clear functions so that I could animate using fillCircle and fillRectangle functions. Is there any way to clear faster ? I tried removing that delay(10) in clear() function of TFT_22_ILI9225.cpp

**Comment by Nkawu** [comment]
As far as I can remember, the driver chip for this LCD has no native clear function, so I was forced to used fillRectangle. I think you are pushing the limits for this little LCD! Let me know if you do find a method to do this faster.
