### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by donim4rt** [Nkawu/TFT_22_ILI9225#73]
how to increase font size in this library  Nkawu /TFT_22_ILI9225 . thank you

**Comment by EniSy** [comment]
Seems we need a custom font..

**Comment by Nkawu** [comment]
It's in the documentation:

- [Standard Fonts](https://github.com/Nkawu/TFT_22_ILI9225/wiki#standard-fonts)
- [GFX Fonts](https://github.com/Nkawu/TFT_22_ILI9225/wiki#gfx-fonts)
