### ISSUE TITLE
Problems to set ONLY Color

### ISSUE THREAD

**Issue by nvillamor** [Nkawu/TFT_22_ILI9225#75]
How change de drawText color from variable?

I try yo change the color from different condition of my program to ser in a variable example color = "COLOR_GREEN"

But...
color = "COLOR_GREEN";
tft.drawText(0,0,"TEXT Color",color);

no matching function for call to 'TFT_22_ILI9225::drawText(int, int, StringSumHelper&, String&)'

**Comment by charclo** [comment]
Try changing color = "COLOR_GREEN"; to
int color = COLOR_GREEN;
The function drawtext expects an int as the fourth argument, COLOR_GREEN is just a macro that defines an int

**Comment by nvillamor** [comment]
Excellent, thanks @charclo works great!
