### ISSUE TITLE
How can display € character with defaults fonts?

### ISSUE THREAD

**Issue by nvillamor** [Nkawu/TFT_22_ILI9225#76]
How can display € character with defaults fonts?
Only can $ character

It's possible add only 1 character?

Regards.

**Comment by Nkawu** [comment]
You can create any font and character, it's in the documentation:

- [Standard Fonts](https://github.com/Nkawu/TFT_22_ILI9225/wiki#standard-fonts)
- [GFX Fonts](https://github.com/Nkawu/TFT_22_ILI9225/wiki#gfx-fonts)
