### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by orlait** [Nkawu/TFT_22_ILI9225#8]
Здравствуйте! 
Не могли бы Вы добавить в библиотеку числовые шрифты больших размеров.

**Comment by Nkawu** [comment]
It is easy to create fonts yourself, instructions in the Wiki: https://github.com/Nkawu/TFT_22_ILI9225/wiki#standard-fonts and also https://learn.adafruit.com/adafruit-gfx-graphics-library/using-fonts
